baseurl = "https://userexe.me"
title = "user.exe"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[params.utterances]
  repo = "mrhappyma/userexedotme" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "on-site comments" # https://utteranc.es/#heading-issue-label
  theme = "preferred-color-scheme" # https://utteranc.es/#heading-theme

[params]
  author = "Dominic Ruggiero"
  info = "human (attempting) learning back-end development"
  description = "Dominic's *fun* personal website"
  keywords = "blog,developer,personal"
#  avatarurl = "images/avatar.jpg"
  gravatar = "dominic@userexe.me"

  #favicon_32 = "/img/favicon-32x32.png"
 # favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mrhappyma/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/user____exe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"