baseurl = "https://userexe.me"
title = "Dominic Ruggiero"
info = "human being trying to learn back-end development"
description = "Dominic Ruggiero's *fun* website"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[params.utterances]
  repo = "mrhappyma/userexedotme" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "on-site comments" # https://utteranc.es/#heading-issue-label
  theme = "preferred-color-scheme" # https://utteranc.es/#heading-theme