name: PR
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Report
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: josephduffy/wait-for-netlify-action@v1
        id: wait-for-netflify-preview
        with:
          site_name: "userexedotme"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
              ${{ steps.wait-for-netflify-preview.outputs.url }}
      - name: Post Lighthouse Status
        uses: manrueda/lighthouse-report-action@v1.1.2
        with:
          reports: '.lighthouseci'
          github-token: ${{ secrets.GITHUB_TOKEN }}
